name: A-TO-B:CUSTOM_BRANCH
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Build and Deploy
       uses: xscd-16/blog@master
       env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: xscd-16/cimu_blog
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy
